# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cache_service.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import payload_pb2 as payload__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='cache_service.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x13\x63\x61\x63he_service.proto\x1a\rpayload.proto2T\n\x0c\x43\x61\x63heService\x12!\n\nsetContent\x12\x08.Request\x1a\t.Response\x12!\n\ngetContent\x12\x08.Request\x1a\t.Responseb\x06proto3'
  ,
  dependencies=[payload__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_CACHESERVICE = _descriptor.ServiceDescriptor(
  name='CacheService',
  full_name='CacheService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=38,
  serialized_end=122,
  methods=[
  _descriptor.MethodDescriptor(
    name='setContent',
    full_name='CacheService.setContent',
    index=0,
    containing_service=None,
    input_type=payload__pb2._REQUEST,
    output_type=payload__pb2._RESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getContent',
    full_name='CacheService.getContent',
    index=1,
    containing_service=None,
    input_type=payload__pb2._REQUEST,
    output_type=payload__pb2._RESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CACHESERVICE)

DESCRIPTOR.services_by_name['CacheService'] = _CACHESERVICE

# @@protoc_insertion_point(module_scope)
