# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cache_service.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import payload_pb2 as payload__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='cache_service.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x13\x63\x61\x63he_service.proto\x1a\rpayload.proto2\x0e\n\x0c\x43\x61\x63heServiceb\x06proto3'
  ,
  dependencies=[payload__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_CACHESERVICE = _descriptor.ServiceDescriptor(
  name='CacheService',
  full_name='CacheService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=38,
  serialized_end=52,
  methods=[
])
_sym_db.RegisterServiceDescriptor(_CACHESERVICE)

DESCRIPTOR.services_by_name['CacheService'] = _CACHESERVICE

# @@protoc_insertion_point(module_scope)
