# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: membership.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='membership.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x10membership.proto\"*\n\tHeartBeat\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\t\")\n\tResultMsg\x12\x0f\n\x07succeed\x18\x01 \x01(\x08\x12\x0b\n\x03msg\x18\x02 \x01(\t2A\n\x14MembershipManagement\x12)\n\rSendHeartBeat\x12\n.HeartBeat\x1a\n.ResultMsg\"\x00\x62\x06proto3'
)




_HEARTBEAT = _descriptor.Descriptor(
  name='HeartBeat',
  full_name='HeartBeat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='HeartBeat.address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='port', full_name='HeartBeat.port', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=62,
)


_RESULTMSG = _descriptor.Descriptor(
  name='ResultMsg',
  full_name='ResultMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='succeed', full_name='ResultMsg.succeed', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg', full_name='ResultMsg.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=105,
)

DESCRIPTOR.message_types_by_name['HeartBeat'] = _HEARTBEAT
DESCRIPTOR.message_types_by_name['ResultMsg'] = _RESULTMSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HeartBeat = _reflection.GeneratedProtocolMessageType('HeartBeat', (_message.Message,), {
  'DESCRIPTOR' : _HEARTBEAT,
  '__module__' : 'membership_pb2'
  # @@protoc_insertion_point(class_scope:HeartBeat)
  })
_sym_db.RegisterMessage(HeartBeat)

ResultMsg = _reflection.GeneratedProtocolMessageType('ResultMsg', (_message.Message,), {
  'DESCRIPTOR' : _RESULTMSG,
  '__module__' : 'membership_pb2'
  # @@protoc_insertion_point(class_scope:ResultMsg)
  })
_sym_db.RegisterMessage(ResultMsg)



_MEMBERSHIPMANAGEMENT = _descriptor.ServiceDescriptor(
  name='MembershipManagement',
  full_name='MembershipManagement',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=107,
  serialized_end=172,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendHeartBeat',
    full_name='MembershipManagement.SendHeartBeat',
    index=0,
    containing_service=None,
    input_type=_HEARTBEAT,
    output_type=_RESULTMSG,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MEMBERSHIPMANAGEMENT)

DESCRIPTOR.services_by_name['MembershipManagement'] = _MEMBERSHIPMANAGEMENT

# @@protoc_insertion_point(module_scope)
