## TODO: add content <--> cache communication function in this file: (Assignee: Jie)

## This class should extends XXXServicer generated by proto
class ContentManager():
    def __init__(self):
        pass