# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import membership_pb2 as membership__pb2


class MembershipManagementStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendHeartBeat = channel.unary_unary(
                '/MembershipManagement/SendHeartBeat',
                request_serializer=membership__pb2.HeartBeat.SerializeToString,
                response_deserializer=membership__pb2.ResultMsg.FromString,
                )


class MembershipManagementServicer(object):
    """Missing associated documentation comment in .proto file"""

    def SendHeartBeat(self, request, context):
        """Send heartbeat
        A client to server function call
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MembershipManagementServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendHeartBeat': grpc.unary_unary_rpc_method_handler(
                    servicer.SendHeartBeat,
                    request_deserializer=membership__pb2.HeartBeat.FromString,
                    response_serializer=membership__pb2.ResultMsg.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MembershipManagement', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MembershipManagement(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def SendHeartBeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MembershipManagement/SendHeartBeat',
            membership__pb2.HeartBeat.SerializeToString,
            membership__pb2.ResultMsg.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
